-- ============================================================
-- V1 - Schema completo (PostgreSQL / Supabase)
-- Baseline reconstruida a partir das entidades JPA e do backup de PRODUTOS
-- do Oracle ADB. As migrations Oracle antigas estao em db/legacy-oracle.
--
-- O Flyway executa com search_path = app_luigarah
-- (spring.flyway.default-schema), por isso os nomes nao sao qualificados.
-- ============================================================

--------------------------
-- Sequences (nomes usados pelos @SequenceGenerator das entidades)
--------------------------
CREATE SEQUENCE identidade_seq         START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE produtos_seq           START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE usuarios_seq           START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE enderecos_seq          START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE oauth_providers_seq    START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE carrinho_itens_seq     START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE lista_desejo_itens_seq START WITH 1 INCREMENT BY 1;

--------------------------
-- Identidades (homem, mulher, unissex, infantil)
--------------------------
CREATE TABLE identidades (
    id               BIGINT       PRIMARY KEY DEFAULT nextval('identidade_seq'),
    codigo           VARCHAR(50)  NOT NULL UNIQUE,
    nome             VARCHAR(100) NOT NULL,
    ordem            INTEGER,
    ativo            VARCHAR(1)   DEFAULT 'S' CHECK (ativo IN ('S', 'N')),
    data_criacao     TIMESTAMP    NOT NULL DEFAULT now(),
    data_atualizacao TIMESTAMP
);
ALTER SEQUENCE identidade_seq OWNED BY identidades.id;

--------------------------
-- Produtos
--------------------------
CREATE TABLE produtos (
    id               BIGINT         PRIMARY KEY DEFAULT nextval('produtos_seq'),
    titulo           VARCHAR(255)   NOT NULL,
    subtitulo        VARCHAR(255)   NOT NULL,
    autor            VARCHAR(255)   NOT NULL,
    descricao        TEXT           NOT NULL,
    preco            NUMERIC(19, 2) NOT NULL,
    dimensao         VARCHAR(100)   NOT NULL,
    imagem           TEXT           NOT NULL,
    imagem_hover     TEXT,
    imagens          TEXT,
    composicao       TEXT           NOT NULL,
    destaques        TEXT,
    categoria        VARCHAR(50)    NOT NULL CHECK (categoria IN ('bolsas', 'roupas', 'sapatos')),
    modelo           TEXT,
    padrao_tamanho   VARCHAR(10)    CHECK (padrao_tamanho IN ('usa', 'br', 'sapatos')),
    identidade_id    BIGINT         REFERENCES identidades (id) ON DELETE SET NULL,
    data_criacao     TIMESTAMP      NOT NULL DEFAULT now(),
    data_atualizacao TIMESTAMP      NOT NULL DEFAULT now()
);
ALTER SEQUENCE produtos_seq OWNED BY produtos.id;

CREATE INDEX idx_produtos_categoria  ON produtos (categoria);
CREATE INDEX idx_produtos_titulo     ON produtos (titulo);
CREATE INDEX idx_produtos_autor      ON produtos (autor);
CREATE INDEX idx_produtos_identidade ON produtos (identidade_id);

--------------------------
-- Catalogo de tamanhos
--------------------------
CREATE TABLE tamanhos (
    id        BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria VARCHAR(20) NOT NULL CHECK (categoria IN ('roupas', 'sapatos')),
    etiqueta  VARCHAR(40) NOT NULL,
    padrao    VARCHAR(10) NOT NULL CHECK (padrao IN ('usa', 'br', 'sapatos')),
    ordem     INTEGER,
    CONSTRAINT uq_tamanho_cat_padrao UNIQUE (categoria, padrao, etiqueta)
);

CREATE TABLE produtos_tamanhos (
    produto_id  BIGINT  NOT NULL REFERENCES produtos (id) ON DELETE CASCADE,
    tamanho_id  BIGINT  NOT NULL REFERENCES tamanhos (id) ON DELETE CASCADE,
    qtd_estoque INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT pk_produtos_tamanhos PRIMARY KEY (produto_id, tamanho_id)
);
CREATE INDEX idx_pt_tamanho ON produtos_tamanhos (tamanho_id);

-- Estoque consolidado (bolsas / produtos sem tamanho)
CREATE TABLE produtos_estoque (
    produto_id  BIGINT  PRIMARY KEY REFERENCES produtos (id) ON DELETE CASCADE,
    qtd_estoque INTEGER NOT NULL DEFAULT 0
);

--------------------------
-- Usuarios e autenticacao
--------------------------
CREATE TABLE usuarios (
    id               BIGINT       PRIMARY KEY DEFAULT nextval('usuarios_seq'),
    nome             VARCHAR(100) NOT NULL,
    sobrenome        VARCHAR(100),
    email            VARCHAR(255) NOT NULL UNIQUE,
    senha            VARCHAR(255),
    telefone         VARCHAR(20),
    data_nascimento  DATE,
    genero           VARCHAR(20),
    foto_perfil      VARCHAR(500),
    role             VARCHAR(20)  NOT NULL DEFAULT 'USER' CHECK (role IN ('USER', 'ADMIN')),
    ativo            BOOLEAN      NOT NULL DEFAULT TRUE,
    email_verificado BOOLEAN      NOT NULL DEFAULT FALSE,
    provider         VARCHAR(20)  CHECK (provider IN ('LOCAL', 'GOOGLE', 'FACEBOOK', 'GITHUB')),
    provider_id      VARCHAR(255),
    data_criacao     TIMESTAMP    NOT NULL DEFAULT now(),
    data_atualizacao TIMESTAMP,
    ultimo_acesso    TIMESTAMP
);
ALTER SEQUENCE usuarios_seq OWNED BY usuarios.id;

CREATE TABLE oauth_providers (
    id          BIGINT       PRIMARY KEY DEFAULT nextval('oauth_providers_seq'),
    usuario_id  BIGINT       NOT NULL REFERENCES usuarios (id) ON DELETE CASCADE,
    provider    VARCHAR(50)  NOT NULL,
    provider_id VARCHAR(255),
    created_at  TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at  TIMESTAMP,
    CONSTRAINT uq_oauth_usuario_provider UNIQUE (usuario_id, provider)
);
ALTER SEQUENCE oauth_providers_seq OWNED BY oauth_providers.id;

CREATE TABLE enderecos (
    id               BIGINT       PRIMARY KEY DEFAULT nextval('enderecos_seq'),
    usuario_id       BIGINT       NOT NULL REFERENCES usuarios (id) ON DELETE CASCADE,
    pais             VARCHAR(100) NOT NULL,
    estado           VARCHAR(100) NOT NULL,
    cidade           VARCHAR(100) NOT NULL,
    cep              VARCHAR(20)  NOT NULL,
    bairro           VARCHAR(200),
    rua              VARCHAR(300),
    numero           VARCHAR(20),
    complemento      VARCHAR(200),
    principal        BOOLEAN      NOT NULL DEFAULT FALSE,
    data_criacao     TIMESTAMP    NOT NULL DEFAULT now(),
    data_atualizacao TIMESTAMP
);
ALTER SEQUENCE enderecos_seq OWNED BY enderecos.id;
CREATE INDEX idx_enderecos_usuario ON enderecos (usuario_id);

CREATE TABLE verification_tokens (
    id        BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo    VARCHAR(6)   NOT NULL,
    token     VARCHAR(500) NOT NULL UNIQUE,
    email     VARCHAR(255) NOT NULL,
    tipo      VARCHAR(50)  NOT NULL CHECK (tipo IN ('VERIFICACAO_EMAIL', 'RESET_SENHA')),
    criado_em TIMESTAMP    NOT NULL,
    expira_em TIMESTAMP    NOT NULL,
    usado     BOOLEAN      NOT NULL DEFAULT FALSE,
    usado_em  TIMESTAMP
);
CREATE INDEX idx_vtoken_codigo     ON verification_tokens (codigo);
CREATE INDEX idx_vtoken_email_tipo ON verification_tokens (email, tipo);
CREATE INDEX idx_vtoken_expira_em  ON verification_tokens (expira_em);

--------------------------
-- Carrinho e lista de desejos
--------------------------
CREATE TABLE carrinho_itens (
    id               BIGINT    PRIMARY KEY DEFAULT nextval('carrinho_itens_seq'),
    usuario_id       BIGINT    NOT NULL REFERENCES usuarios (id) ON DELETE CASCADE,
    produto_id       BIGINT    NOT NULL REFERENCES produtos (id) ON DELETE CASCADE,
    tamanho_id       BIGINT    REFERENCES tamanhos (id) ON DELETE CASCADE,
    quantidade       INTEGER   NOT NULL CHECK (quantidade BETWEEN 1 AND 99),
    data_adicao      TIMESTAMP NOT NULL DEFAULT now(),
    data_atualizacao TIMESTAMP,
    -- NULLS NOT DISTINCT (PG 15+) reproduz o comportamento do Oracle para bolsas (tamanho_id NULL)
    CONSTRAINT uq_carrinho_usuario_produto_tamanho
        UNIQUE NULLS NOT DISTINCT (usuario_id, produto_id, tamanho_id)
);
ALTER SEQUENCE carrinho_itens_seq OWNED BY carrinho_itens.id;
CREATE INDEX idx_carrinho_produto ON carrinho_itens (produto_id);

CREATE TABLE lista_desejo_itens (
    id          BIGINT    PRIMARY KEY DEFAULT nextval('lista_desejo_itens_seq'),
    usuario_id  BIGINT    NOT NULL REFERENCES usuarios (id) ON DELETE CASCADE,
    produto_id  BIGINT    NOT NULL REFERENCES produtos (id) ON DELETE CASCADE,
    data_adicao TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT uq_lista_desejo_usuario_produto UNIQUE (usuario_id, produto_id)
);
ALTER SEQUENCE lista_desejo_itens_seq OWNED BY lista_desejo_itens.id;
CREATE INDEX idx_lista_desejo_produto ON lista_desejo_itens (produto_id);

--------------------------
-- Seguranca Supabase: o backend conecta como dono das tabelas (ignora RLS).
-- RLS sem policies bloqueia qualquer acesso via Data API (anon/authenticated)
-- caso este schema venha a ser exposto no painel.
--------------------------
ALTER TABLE identidades         ENABLE ROW LEVEL SECURITY;
ALTER TABLE produtos            ENABLE ROW LEVEL SECURITY;
ALTER TABLE tamanhos            ENABLE ROW LEVEL SECURITY;
ALTER TABLE produtos_tamanhos   ENABLE ROW LEVEL SECURITY;
ALTER TABLE produtos_estoque    ENABLE ROW LEVEL SECURITY;
ALTER TABLE usuarios            ENABLE ROW LEVEL SECURITY;
ALTER TABLE oauth_providers     ENABLE ROW LEVEL SECURITY;
ALTER TABLE enderecos           ENABLE ROW LEVEL SECURITY;
ALTER TABLE verification_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE carrinho_itens      ENABLE ROW LEVEL SECURITY;
ALTER TABLE lista_desejo_itens  ENABLE ROW LEVEL SECURITY;
